lfit/releng-reusable-workflows

.github/workflows/verify.yaml, .pre-commit-config.yaml, .readthedocs.yml
* Disable actionlint pre-commit when run through pre-commit.ci
* Add a special verify GHA for running actionlint and validating commit
messages since that is _also_ not run through pre-commit.ci
* Correct minor yaml formatting warning caught when getting this enabled
=> CI: Properly configure pre-commit for actionlint

.github/workflows/verify.yaml
The action being used to check the commit-message meets our Semantic
Pull Request criteria only supports happening during a pull_request or
pull_request_target event. Make sure it doesn't fire on push events.
=> CI: commit-message check during PR only

.github/workflows/gerrit-ci-management-merge.yaml
Use standard checkout action on HEAD of the
input branch.
=> Fix: Use standard checkout for merge workflow

.github/workflows/gerrit-ci-management-merge.yaml
Make a comment at the start of job and another with the job conclusion
onto the Gerrit change that triggered the job.
=> Feat: Make start / finish announcements to Gerrit

.github/workflows/gerrit-required-info-yaml-verify.yaml
The required INFO file scanner needs to always pass if there are no
INFO.yaml files present. Otherwise, it should fail if there are files
modified along with the INFO.yaml. Finally, if it is just the INFO.yaml
file, then it should do the standard validation scanning.
=> Fix: Correct logic for INFO file required job

.github/workflows/gerrit-ci-management-merge.yaml, .github/workflows/gerrit-ci-management-verify.yaml, .github/workflows/gerrit-required-info-yaml-verify.yaml
To protect against multiple workflows for the same ChangeID possibly
trampling on each other we need to make sure that we have unique
information in the concurrency group
=> CI: Add additional info to concurrency

.github/workflows/gerrit-compose-ci-management-verify.yaml
Strip off the voting syntax to make this callable without doing any
voting. The intent is that the calling workflow will add the needed
voting bits around this and that it all "just works"
=> Feat: Create a "composable" reusable ci-man verify

.github/workflows/compose-packer-verify.yaml
- Update build params with defaults params to be able to run workflows manually on a forked repo.
- Installs the default version of packer to v1.9.1
- Use the latest version v0.4 lfit/checkout-gerrit-change-action allow passing the GHA PAT token for all the jobs in the workflow file.
- Use base64 encode / decode to handle special characters correctly while storing and retriving secrets to/from GHA. Writing secrets CLI dependent config files results in an undefined behavior.
- The change requires creating secrets before hand on project with secret name as CLOUDS_YAML_B64 and CLOUDS_ENV_B64 along with the $key-value pairs in yaml and hcl format and base64 encoded.
=> Feat: Add packer verify Github Actions to workflow

.github/workflows/compose-repo-linting.yaml
We have a common workflow of validating actionlint and pre-commit on any
repositories as two separate jobs inside the workflow. This will allow
this to be more modular
=> Feat: Create basic repo linting workflow compose

.github/workflows/compose-packer-verify.yaml
* Re-order the job so that it checks to see if packer files have changed
before doing any other work.
* Limit token permissions to just read
* Give all steps a name
=> Refactor: Re-arrange compose-packer-verify

.github/workflows/composed-ci-management-verify.yaml
A single workflow that can be consumed to vote (or not) that does the
following:
* standard repository linting
* JJB verification
* Packer verification
=> Feat: Composed ci-management verify workflow

.github/workflows/compose-packer-verify.yaml
GitHub Actions makes it possible to do collapsed log lines with some
echod commands to the runner. This makes the logs easier to read.
=> CI: Add output grouping for packer

.github/workflows/compose-jjb-verify.yaml, .github/workflows/compose-repo-linting.yaml, .github/workflows/gerrit-ci-management-merge.yaml, .github/workflows/gerrit-ci-management-verify.yaml, .github/workflows/gerrit-compose-ci-management-verify.yaml, .github/workflows/gerrit-compose-required-info-yaml-verify.yaml, .github/workflows/gerrit-required-info-yaml-verify.yaml
* Upgrade to v0.5 with frozen SHA
* Use new submodules directive where possible to save a step
* Add needed linting lines for new long lines
=> Chore: Upgrade Gerrit checkout to v0.5

.github/workflows/gerrit-ci-management-merge.yaml
The latest version of python-jenkins 1.8.1 and JJB 5.0.4 support urllib3 newer DEFAULT_TIMEOUT, therefore unpin urllib3<2.0.0
=> CI: Unpin urllib3<2.0.0 with JJB 5.0.4

.github/workflows/gerrit-compose-required-rtdv3-merge.yaml, .github/workflows/gerrit-compose-required-rtdv3-verify.yaml
Allow the rtdv3 workflows to be used as required or be used at the repository level.
=> CI: Update rtdv3 verify and merge workflows

.github/workflows/compose-info-yaml-verify.yaml, .github/workflows/compose-jjb-verify.yaml, .github/workflows/compose-packer-verify.yaml, .github/workflows/compose-repo-linting.yaml, .github/workflows/gerrit-ci-management-verify.yaml, .github/workflows/gerrit-compose-ci-management-verify.yaml, .github/workflows/gerrit-compose-required-rtdv3-verify.yaml, .github/workflows/gerrit-required-info-yaml-verify.yaml
* Upgrades all calls for checkout-gerrit-change-action from v0.5 to v0.6
* Renames gerrit-compose-required-info-yaml-verify ->
compose-info-yaml-verify which more correctly matches how the file
should be named
=> Chore: Upgrade to gerrit checkout v0.6

.github/workflows/gerrit-compose-required-rtdv3-merge.yaml
- Do not re-run verify on rtdv3 merge workflow
- Clone the caller repo not the local one
=> Fix: Restructure rtdv3 merge job

.github/workflows/gerrit-compose-required-maven-verify.yaml
- We do not need to display the version again
- batch-mode option cannot be passed via opts
=> Fix: Remove additional maven opts

.github/workflows/compose-maven-verify.yaml
The carrot symbol ('^') set in Jenkins maven settings.xml file
(ci-man/jenkins-config/managed-config-files/globalMavenSettings)
is used for escaping the '${}' by the JCASC plugin scripts.
Maven does not recognize these symbols. Therefore the file needs
to be processed to remove the prefixed carrot symbol before its
used in GHA workflow or would return the below error while
resolving dependencies.
Error:
Cannot access
^https://nexus.opendaylight.org/content/repositories/public/
=> Fix: Strip carrot symbol from the settings file

.github/workflows/compose-maven-verify.yaml
ODL maven verify jobs would require passing additional  MAVEN_OPTS such as "-Dkaraf.keep.unpack" therefore this require passing MVN_OPTS as inputs from the downstream project.
=> Fix: Allow passing Maven opts as input

.github/workflows/compose-packer-verify.yaml
Remove bash multi line indent to check if unmarshal yaml errors get resolved.
Ref:
https://github.com/orgs/community/discussions/65057
=> Fix: Rm shell multiline

.github/workflows/compose-packer-verify.yaml, .github/workflows/composed-ci-management-verify.yaml
Passing secrets through nested composable workflows may potentially by reseting the values causing unmarshall errors.
=> Fix: Pass secrets and vars thru env

.github/workflows/composed-ci-management-verify.yaml
Error:
The workflow is not valid. composed-ci-management-verify.yaml@main (Line: 136, Col: 20): Invalid secret, ENV_SECRETS is not defined in the referenced workflow.
=> CI: Define ENV_SECRETS in workflow

.github/workflows/compose-packer-verify.yaml
Error:
composed-ci-management-verify.yaml@main (Line: 148, Col: 20): Invalid secret, ENV_SECRETS is not defined in the referenced workflow.
=> CI: Move secret definition under secrets

.github/workflows/compose-packer-verify.yaml
A workaround to mask printing sensitive info from
workflow logs.
=> Fix: mask sensitive info with ::add-masks::

.github/workflows/composed-ci-management-verify.yaml
This is done to ensure the env printed in the workflow logs does not contain sensitive data.
=> CI: Move input param ENV_SECRETS under secrets

.github/actions/verify-release-schema-action/action.yaml
This action will be used by the release workflows
=> CI: Add action to verify a release file against an approved schema

.github/workflows/compose-packer-verify.yaml
::add-mask:: disables the output however the GHA steps through
the echo in the run. Therefore avoid sensitive data being
echo-ed in the logs being disabled add +x as the last arg
to bash.
Export only required vars into environment.
Signed-off-by: Anil Belur <abelur@linuxfoundation.org>
=> Fix: Disable the bash echo with +x

.github/workflows/gerrit-ci-management-merge.yaml, .github/workflows/gerrit-ci-management-verify.yaml, .github/workflows/gerrit-compose-ci-management-verify.yaml
JJB 6.0.0 is release and our ci-man repos are broken. Pin to the latest working version until our code base is updated with the latest backard incompatibilites.
=> Fix: Pin JJB to 5.1.0

.github/workflows/gerrit-compose-required-rtdv3-verify.yaml
Add missing "six" package to this workflow to address breakage here:
https://jira.linuxfoundation.org/browse/IT-26426
https://github.com/onap/.github/actions/runs/7714805162/job/21027916726
=> Fix: RTD job breakage due to missing dependency

.github/workflows/gerrit-ci-management-merge.yaml, .github/workflows/gerrit-compose-required-rtdv3-merge.yaml, .github/workflows/verify.yaml
Update: actions/checkout@v3 -> actions/checkout@v4
`Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-python@v4. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.`
=> Chore: Update actions/checkout to v4

.github/workflows/compose-jjb-verify.yaml, .github/workflows/gerrit-ci-management-merge.yaml, .github/workflows/gerrit-ci-management-verify.yaml, .github/workflows/gerrit-compose-ci-management-verify.yaml
The present implementation becomes a bottleneck while upgrading ci-man repos to JJB 6.x since all downstream repos cannot be upgraded at the same time.
Set the default version of JJB version as "5.1.0".
Issue: RELENG-5122
=> CI: Allow JJB version to be set through vars

.github/actions/tox-run-action/action.yaml, .github/workflows/gerrit-compose-required-tox-verify.yaml
The previous version of this workflow was based on an incorrect understanding of how GHA would process YAML maps for a matrix. This was being used to specify different workflows for different python versions.
Since this does not work as intended, we will now simply use a single python version, and a list of envs. If the caller would like to run workflows on multiple versions of python, they can still call the workflow again on a different version.
This change also includes improvements to the documentation, particularly focused on improving the user's understanding of how to pass in the env list.
Issue: RELENG-5132
=> Fix: Tox workflow takes only one python version

.github/workflows/gerrit-compose-required-tox-verify.yaml
This is poorly documented, but it is necessary to do this specific checkout step before using a local action.
This should fix the error seen here: https://github.com/o-ran-sc/sim-a1-interface/actions/runs/7875295910/job/21486885240
=> Fix: Use actions/checkout for ref to local action

.github/workflows/gerrit-compose-required-tox-verify.yaml
The tox-run action needs to be checked out into a separate directory, and then referred to with its full path. This makes external repos capable of running the action, as it will no longer be local for the calling project.
=> Fix: Specify remote repo and local path for action

.github/actions/tox-run-action/action.yaml
This is a convenient way to get requirements installed, but requires either requirements.txt or pyproject.toml to be present. Since we don't want the action to fail if these are not present, we can't use it here. Instead, the build-package step will install pyproject.toml requirements, and we will now check for a requirements.txt file while running the shell script that calls tox.
This also adds pipx to the tox call, to ensure that tox and its requirements are present to run tox properly.
=> Fix: Remove "cache: pip" from setup-python call

.github/workflows/compose-docker-release-verify.yaml, .github/workflows/compose-docker-verify.yaml, .github/workflows/compose-gradle-verify.yaml, .github/workflows/compose-info-yaml-verify-testing.yaml, .github/workflows/compose-jjb-verify.yaml, .github/workflows/compose-packer-verify.yaml, .github/workflows/compose-repo-linting.yaml, .github/workflows/gerrit-ci-management-verify.yaml, .github/workflows/gerrit-compose-ci-management-verify.yaml, .github/workflows/gerrit-compose-required-info-yaml-verify.yaml, .github/workflows/gerrit-compose-required-rtdv3-verify.yaml, .github/workflows/gerrit-compose-required-tox-verify.yaml, .github/workflows/gerrit-required-info-yaml-verify.yaml
Pull in fix for handling the git submodule updates fixed in lfit/checkout-gerrit-change-action v0.9.
=> Chore: Update checkout-gerrit-change-action v0.9

.github/workflows/compose-maven-verify.yaml
Use CLI run commands to run maven in a more flexible way. ci-maven-action does not provide a way of passing mvn-params or specific mvn-opts
=> Fix: Switch from using ci-maven-action to using CLI commands

.github/workflows/compose-maven-verify.yaml
The comma was previously needed for the maven action we were using. We should have space separated goals.
=> Fix: Update MVN_PHASES to remove comma separated goals

.github/workflows/compose-maven-verify.yaml
Currently, the global-settings are obtained through a Jenkins fetch, and then via a variable which is concatenated onto what was fetched. This is a problem, as it will create an invalid settings file if both are defined.
To simplify this process, we can simply use the variable. The touch/cat is replaced with an overwrite, as we want the file to be written as it's stored, and not placed on top of anything that is already in the file.
=> Fix: Only obtain global-settings through variable

.github/workflows/compose-maven-verify.yaml
Because the variable is being filled by the action rather than bash, using double quotes is messing with the double quotes that exist within the text of the variable. By using single quotes, bash will handle all text literally, and the variable will still dereference, since that is happening before the script is handed to bash.
=> Fix: Use single quotes for global-settings echo

.github/workflows/compose-jjb-verify.yaml
Change-id is unique to the branch. When a change is cherry-picked onto another branch with the same change-id, then first job that is queued gets cancelled. Therefore use a combination of patchset revision and change-id to avoid collision.
Error:
prepare
Canceling since a higher priority waiting request for 'required-verify-Gerrit Required
Verify-I26669f0da284d54bd6300768977369e11e42553a' exists
Issue: IT-26541
=> Fix: Use patchset revision to avoid collisions

.github/workflows/compose-docker-release-verify.yaml, .github/workflows/compose-docker-verify.yaml, .github/workflows/compose-info-yaml-verify-testing.yaml, .github/workflows/compose-jjb-verify.yaml, .github/workflows/compose-maven-verify.yaml, .github/workflows/compose-packer-verify.yaml, .github/workflows/compose-repo-linting.yaml, .github/workflows/composed-ci-management-verify.yaml, .github/workflows/composed-gradle-nexus-iq.yaml, .github/workflows/composed-maven-nexus-iq.yaml, .github/workflows/gerrit-ci-management-merge.yaml, .github/workflows/gerrit-ci-management-verify.yaml, .github/workflows/gerrit-compose-ci-management-verify.yaml, .github/workflows/gerrit-compose-required-info-yaml-verify.yaml, .github/workflows/gerrit-compose-required-rtdv3-merge.yaml, .github/workflows/gerrit-compose-required-rtdv3-verify.yaml, .github/workflows/gerrit-compose-required-tox-verify.yaml, .github/workflows/gerrit-required-info-yaml-verify.yaml
Change-id is unique to the branch. When a change is cherry-picked onto another branch with the same change-id, then first job that is queued gets cancelled. Therefore use a combination of branch name and change-id to avoid collision.
Error:
Canceling since a higher priority waiting request for 'required-verify-Gerrit Required
Verify-I26669f0da284d54bd6300768977369e11e42553a' exists
The previous commit (0ef949323165) used patchset revision that is now updated to use Gerrit branch name.
Issue: IT-26541
=> Fix: Use branch to avoid collisions

.github/workflows/composed-generic-sonar-cloud.yaml
You should run the goal 'org.sonarsource.scanner.maven:sonar' during build rather than using the composed-maven-sonar-cloud workflow.
Instead, we are converting it as a generic runner to run other code.
=> Fix: Update Maven SonarCloud workflow to make it Generic

.github/workflows/composed-maven-sonar-cloud.yaml
This workflow uses org.sonarsource.scanner.maven:sonar to run the sonar scan after a maven clean install.
=> CI: Add workflow for Maven Sonar Cloud Scan

.github/workflows/composed-gradle-nexus-iq.yaml, .github/workflows/composed-maven-nexus-iq.yaml
The CLM scanner reports a failure if the scan found vulnerabilities. We should allow the jobs to continue since this is the expected result.
Issue-ID: CIMAN-33
=> Fix: Allow CLM workflows to continue on error

.github/actions/tox-run-action/action.yaml, .github/workflows/gerrit-compose-required-tox-verify.yaml
Previously, only a local path could be passed to the action. The action will continue to use just a path, but the verify workflow can now accept a URL (useful for legacy ci-management scripts) or a string as the script.
=> Feat: Allow tox-verify pre-build url, string

.github/workflows/composed-ci-management-verify.yaml, .github/workflows/gerrit-ci-management-merge.yaml, .github/workflows/gerrit-ci-management-verify.yaml, .github/workflows/gerrit-required-info-yaml-verify.yaml
This pulls in the change to skip vote jobs on local runs.
=> Chore: Update gerrit-review-action to v0.7

.github/actions/tox-run-action/action.yaml, .github/workflows/gerrit-compose-required-tox-verify.yaml
We need to run a no-operation to allow the action to continue if there is no prebuild script to run.
=> Fix: Run a no-op bash command when there is no prebuild script

.github/workflows/composed-prescan-sonar-cloud.yaml
This workflow replaces gerrit-maven-sonar-prescan-script from global-jjb.
Please note that this template was named "maven" by mistake but it does not actually run any maven operations. This template calls an optional project script and triggers a SonarCloud scan.
=> CI: Add workflow for prescan SonarCloud

.github/workflows/composed-ci-management-verify.yaml, .github/workflows/gerrit-ci-management-merge.yaml, .github/workflows/gerrit-ci-management-verify.yaml, .github/workflows/gerrit-required-info-yaml-verify.yaml
The conclusion getter was changed to a different action that is
maintained.
=> Fix: Change conclusion getter

.github/actions/tox-run-action/action.yaml
The lftools license check fails the tox run with python 3.12.
The default version of the python used in the tox workflow using python 3.12. Python 3.12 does not come with a stdlib distutils module (changelog), because distutils was deprecated in 3.10 and removed in 3.12. See PEP 632 – Deprecate distutils module.
Therefore, check if python 3.12 and install distutils before the run.
Ref:
https://docs.python.org/3/whatsnew/3.12.html
https://peps.python.org/pep-0632/
Issue: RELENG-5403
=> Fix: Install setuptools for tox jobs with py3.12

.github/workflows/verify.yaml
The semantic commit message validator we were (and still are using) only
validates that the PR matches semantic commit message standard and if
there is a single commit in the PR, that it also matches the PR title.
Since we require that _all_ of our commits meet the standard we needed
to find another way to do this.
=> CI: Enforce semantic commit messages

.github/workflows/compose-gradle-publish.yaml, .github/workflows/compose-packer-verify.yaml, .github/workflows/composed-autotools-sonar-cloud.yaml, .github/workflows/composed-cmake-sonar-cloud.yaml, .github/workflows/composed-generic-sonar-cloud.yaml, .github/workflows/composed-prescan-sonar-cloud.yaml
Address NodeJS 16 -> NodeJS 20 warnings.
As per GitHub post:
2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
Affecting:
actions/setup-java@v3
infovista-opensource/vars-to-env-action@1.0.0
=> Fix: Update actions to address node warnings

.github/actions/maven-build-action/action.yaml, .github/workflows/compose-maven-merge.yaml, .github/workflows/compose-maven-verify.yaml
While there is an input parameter for setting a custom pom.xml file there is no code to actually utilize it. This change fixes that issue and enables the use of alternative pom.xml file path. Also fix the description of parameter to state that its the path to the file and not directory.
=> Fix: Use the Maven pom file provided by input

.github/workflows/compose-maven-verify.yaml
These GERRIT_* inputs are not used at all by the workflow so they should not be required configuration.
=> Fix: Remove requirement for unused parameters

.github/workflows/compose-packer-verify.yaml, .github/workflows/composed-ci-management-verify.yaml
The variable name for CLOUDS_YAML_B64 was incorrect in the composed
ci-man verify workflow.
In compose-packer-verify, we are referencing the CLOUD secrets from
the env. While these may be available in the env after the "Export
env secrets" step, it's still safer to use the secrets context.
Signed-off-by: Eric Ball <eball@linuxfoundation.org>
=> Fix: Correct var name, use secrets rather than env

.github/workflows/compose-packer-verify.yaml
There is an issue with passing secrets through workflows that we haven't figured out yet. This was based on @askb's own work, as he asked and answered here:
https://github.com/orgs/community/discussions/65057
=> Fix: Packer secrets back to env

.github/workflows/compose-packer-verify.yaml, .github/workflows/composed-ci-management-verify.yaml
Problem:
This commit addresses the issue of secret exposure when passing secrets between reusable workflows in GitHub Actions. Automatic secret masking within reusable workflows is lost due to secret inheritance limitations. Additionally, multiline secrets and special characters pose challenges [1.] is undefined with Github actions.
Proposed Solution:
To redact and mask secrets from console logs, I propose the two-step Base64 encoding approach inspired by [2.]:
1. Double Base64 Encoding: Before storing secrets in the organization or repository secret store, encode them twice using the base64 command. This prevents secret exposure when GitHub Actions outputs them.
example:
cat clouds.yaml | base64 -w0 | base64 -w0 > clouds-2xb64.yaml cat clouds-env.pkrvars.hcl | base64 -w0 | base64 -w0 > \ …
=> Fix: Securely mask secrets in Reusable Workflows

.github/workflows/compose-packer-verify.yaml
The present approach re-masks everything that is parsed under secrets, instead mask only the required cloud secrets.
=> Fix: Mask required keys

.github/actions/node-build-action/action.yaml
Required for new ONAP projects, such as portal-ng-ui. Allows the node version and build tool to be specified.
=> Feat: Add node.js build action

README.md
Will pass linting if/when we merge: https://github.com/lfit/releng-reusable-workflows/pull/188
=> Chore: Add naming conventions to documentation

.github/workflows/compose-maven-verify.yaml, .github/workflows/zzci-test-verify-maven.yaml, test/maven-project/pom.xml
This change creates a minimal pom.xml for unit testing of Maven jobs and creates a test job for the Maven Verify workflow. The intent here is to create a small unit test that can quickly validate Maven workflows and catch potential issues that maybe missed by a linter.
=> Test: Create minimal unit test for Maven jobs

.github/actions/pinned-versions-action/action.yaml
Also update upstream actions:
tj-actions/changed-files v45.0.5 -> v45.0.6
zgosalvez/github-actions-ensure-sha-pinned-actions v3.0.17 -> v3.0.20
Tested here:
https://github.com/os-climate/osc-github-devops/blob/main/.github/actions/pinned-versions-action/action.yaml
https://github.com/os-climate/osc-github-devops/actions/runs/12815318046/job/35733737004
=> Chore: Tidy up file diff and scoping behaviour

.github/workflows/reuse-verify-github-actions.yaml, .github/workflows/verify-github-actions.yaml
Update local repository verification job (that checks actions/workflows for SHA commit values) to comply with reusable workflow naming convention. Also, pins version used to commit SHA values.
=> Chore: Pin to commit SHAs, update workflow label

.github/workflows/gerrit-compose-required-rtdv3-verify.yaml
Use Python version from the docs/tox.ini file, if present. Bump Python default from 3.8 -> 3.9 so workflows use a version that is current and not EOL.
Addresses issue raised in support ticket: IT-27705
=> Fix: Docs jobs failures due to Python version mismatches

.github/actions/maven-build-action/action.yaml
When the java-version input is unset, s4u/setup-maven-action defaults to JDK "17" and results in maven verify job failures. ODL requires more recent LTS release of JDK 21.
=> Fix: Set java-version for s4u/setup-maven-action

.github/workflows/compose-docker-verify.yaml, .github/workflows/compose-maven-merge.yaml, .github/workflows/compose-maven-verify.yaml, .github/workflows/compose-packer-verify.yaml, .github/workflows/composed-maven-nexus-iq.yaml, .github/workflows/composed-maven-sonar-cloud.yaml, .github/workflows/gerrit-ci-management-merge.yaml, .github/workflows/gerrit-compose-required-rtdv3-merge.yaml, .github/workflows/openssf-scorecard.yaml
A recent dependabot update highlighted several places where the actions
in use were not pinned to a specific version. This is a security risk.
* Pin versions of actions in use
* Add needed yamllint carve outs where needed to pass proper linting
=> CI: Pin GitHub Actions in use

.github/workflows/call-gerrit-nodejs-sonatype-lifecycle.yaml, .github/workflows/composed-tox-sonar-cloud.yaml, .github/workflows/gerrit-compose-required-tox-verify.yaml, .github/workflows/verify.yaml
This pull request is created by [StepSecurity](https://app.stepsecurity.io/securerepo) at the request of @tykeal. Please merge the Pull Request to incorporate the requested changes. Please tag @tykeal on your message if you have any questions related to the PR.
GitHub Action tags and Docker tags are mutable. This poses a security risk. GitHub's Security Hardening guide recommends pinning actions to full length commit.
- [GitHub Security Guide](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions)
- [The Open Source Security Foundation (OpenSSF) Security Guide](https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies)
For bug reports, feature requests, and general feedback; please email …
=> CI: Harden GitHub Actions

.prettierignore
Workaround for prettier bug in versions prior to 3.4.0 affecting markdown files. Ignore them and defer to markdownlint instead.
=> Chore: Add .prettierignore to skip markdown files

.github/actions/url-validity-check-action/README.md, .github/actions/url-validity-check-action/action.yaml
A bug was introduced at the time this action was imported/migrated over from OS Climate. Previously, it was used to build compound URLs for checking PyPI packages. That functionality was replaced, and this action should be simplfied to perform a basic action. Any compoound handling of URLs needs to be performed elsewhere.
=> Fix: Remove remnants of compound URL handling

.pre-commit-config.yaml, .prettierignore
Looks like the recent .prettierignore addition has introduced occasional linting failures (this does not happen every time linting runs). e.g.
prettier.................................................................Failed [error] No files matching the given patterns were found
This change removes its configuration and we will rely on other tools going forward.
=> Fix: Remove prettier due to various ongoing issues/maintenance concerns

.github/actions/git-commit-message-action/README.md, .github/actions/git-commit-message-action/action.yaml
Now reports when the commit message contains a Gerrit Change-Id
and DCO signed-off-by line. Also, makes the commit number to use
a configurable input parameter.
Tested:
https://github.com/onap/portal-ng-ui/actions/runs/13700431427/job/38313059221
=> Feat: Additional parsing steps and outputs in git-commit-message-action

.pre-commit-config.yaml
autofix_commit_msg -> autoupdate_commit_msg
Reference: https://pre-commit.ci/#configuration-autoupdate_commit_msg
=> CI: Typo in pre-commit configuration

.github/workflows/zzci-test-verify-maven.yaml
The maven-verify workflow was being triggered unnecessarily, even when unrelated files were modified, leading to wasted compute resources. This update ensures the workflow runs only when files under the specified path are changed.
=> Fix: Trigger maven-verify on relevant path changes

.github/workflows/compose-maven-verify.yaml
Using actions/checkout is a bug since the workflows are primarily designed be used for gerrit repositories. The workflows servicing gerrit repos must use the lfit/checkout-gerrit-change-action for checkouts. This ensures the refspec is used while checking out the repo.
=> Fix: Use lfit/checkout-gerrit-change-action

.pre-commit-config.yaml
Addresses unmergeable state of pre-commit.ci automatic updates e.g. https://github.com/lfit/releng-reusable-workflows/pull/373
Should fix gitlint complaint:
1: CC1 Body does not contain a 'Signed-off-by' line
3: B5 Body message is too short (8<20): "updates:"
=> Fix: pre-commit-ci autoupdate commit message format

.github/workflows/compose-maven-verify.yaml
The repository is already set in checkout-gerrit-change-action and not required to be passed.
Error:
Error: Invalid repository 'controller'. Expected format {owner}/{repo}.
=> Fix: Remove optional input for maven verify

.github/workflows/compose-maven-verify.yaml
The checkout-gerrit-change-action requires the gerrit-project input to
be passed but it was not. For some reason GitHub Actions is not failing
the workflow when it gets to the checkout step.
=> Fix: Pass gerrit-project in compose-maven-verify

.github/workflows/gerrit-compose-required-rtdv3-merge.yaml, .github/workflows/gerrit-compose-required-rtdv3-verify.yaml
The RTD validation workflows fail when running lftools commands with:
```
TypeError: deprecated() got an unexpected keyword argument 'name'
File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 3263
```
The workflows install `cryptography<3.4` (version 3.3.2 from 2021), which is incompatible with the system-installed pyOpenSSL package on modern Ubuntu runners (24.04/Python 3.12).
Remove the outdated `cryptography<3.4` constraint and let pip resolve compatible versions automatically.
- **gerrit-compose-required-rtdv3-verify.yaml**: Remove cryptography pin
- **gerrit-compose-required-rtdv3-merge.yaml**: Remove cryptography pin
```diff
- pip install lftools 'niet~=1.4.2' 'cryptography<3.4' yq tox
+ pip install lftools 'niet~=1.4.2' yq tox
```
**Option 1 (Implemented):** Remove the …
=> Fix: Remove outdated cryptography version pin from RTD workflows
