- .github/workflows/gerrit-ci-management-merge.yaml
Add gerrit-ci-management-merge reusable workflow
> CI: Add Gerrit ci-man Merge workflow

- .github/workflows/gerrit-ci-management-merge.yaml
Add "--conf" option to force the use of the right
config file.
> Fix: Force jjb's config file

- .github/workflows/gerrit-required-info-yaml-verify.yaml
Fix variable asociation in workflow
> Fix: Fix typo in INFO verify workflow

- .github/workflows/gerrit-required-info-yaml-verify.yaml
Need to unstall dependency jsonschema
> Fix: Install jsonschema before running validation

- .github/workflows/gerrit-required-info-yaml-verify.yaml
Also needed for INFO validate step
> Fix: Install yaml dependency

- .github/workflows/gerrit-compose-required-info-yaml-verify.yaml
> CI: Make composable INFO Yaml verify

- .github/workflows/gerrit-compose-ci-management-verify.yaml
- .github/workflows/gerrit-compose-required-info-yaml-verify.yaml
> Refactor: Set composable workflow names to match

- .github/workflows/compose-jjb-verify.yaml
> Feat: Move JJB validation to one composition

- .github/workflows/compose-rtdv3-verify.yaml
RTDV3 global reusable verify workflow
> CI: Add rtdv3 verify compose workflow

- .github/workflows/compose-packer-verify.yaml
- .github/workflows/composed-ci-management-verify.yaml
- Test: Set packer verify call to track main
- Chore: Upgrade gerrit checkout to v0.5
> Test: debug packer

- .github/workflows/compose-jjb-verify.yaml
- .github/workflows/compose-repo-linting.yaml
- .github/workflows/verify.yaml
> Fix: Remove forced permissions set on composes

- .github/workflows/compose-info-yaml-verify-testing.yaml
> Test: Create testing info verify compose

- .github/workflows/compose-rtdv3-verify.yaml
This is meanwhile we test this in a single repo
> Fix: Remove Target repo from rtdv3 verify

- .github/workflows/compose-rtdv3-merge.yaml
This workflow calls rtdv3 verify and runs a merge action
> CI: Add rtdv3 merge compose workflow

- .github/workflows/gerrit-compose-required-maven-verify.yaml
The Project specific Maven and JDK version needs to be passed from the downstream workflow that calls the reusable worklow.
> Feat: Add maven verify reusable workflow

- .github/workflows/gerrit-compose-required-maven-verify.yaml
- Added profile activation option
- Added optional pom.xml location
> Fix: Add additional needed params to maven build

- .github/workflows/compose-maven-verify.yaml
- This should not be a required workflow
- Should not use the gerrit nomenclature
> Fix: Update maven verify workflow

- .github/workflows/compose-docker-release-verify.yaml
- .github/workflows/compose-docker-verify.yaml
- .github/workflows/compose-gradle-verify.yaml
- .github/workflows/compose-info-yaml-verify-testing.yaml
- .github/workflows/compose-jjb-verify.yaml
- .github/workflows/compose-packer-verify.yaml
- .github/workflows/compose-repo-linting.yaml
- .github/workflows/composed-ci-management-verify.yaml
- .github/workflows/gerrit-ci-management-merge.yaml
- .github/workflows/gerrit-ci-management-verify.yaml
- .github/workflows/gerrit-compose-ci-management-verify.yaml
- .github/workflows/gerrit-compose-required-info-yaml-verify.yaml
- .github/workflows/gerrit-compose-required-rtdv3-verify.yaml
- .github/workflows/gerrit-compose-required-tox-verify.yaml
- .github/workflows/gerrit-required-info-yaml-verify.yaml
- .pre-commit-config.yaml
- Chore: Update pre-commit hooks (frozen)
- Chore: Update gerrit actions to latest versions
> Chore: Update pre-commit and gerrit actions

- .github/workflows/compose-docker-release-verify.yaml
- .github/workflows/compose-docker-verify.yaml
- .github/workflows/compose-gradle-verify.yaml
- .github/workflows/compose-info-yaml-verify-testing.yaml
- .github/workflows/compose-jjb-verify.yaml
- .github/workflows/compose-packer-verify.yaml
- .github/workflows/compose-repo-linting.yaml
- .github/workflows/gerrit-ci-management-verify.yaml
- .github/workflows/gerrit-compose-ci-management-verify.yaml
- .github/workflows/gerrit-compose-required-info-yaml-verify.yaml
- .github/workflows/gerrit-compose-required-rtdv3-verify.yaml
- .github/workflows/gerrit-compose-required-tox-verify.yaml
- .github/workflows/gerrit-required-info-yaml-verify.yaml
Pull in fix for handling the git submodule updates.
Issue: RELENG-5139
> Chore: Update checkout-gerrit-change-action v0.8

- .github/workflows/compose-maven-verify.yaml
Use GLOBAL_SETTINGS var instead of downloading the file from GH
> Fix: Use GLOBAL_SETTINGS var for global_settings.xml

- .github/actions/tox-run-action/action.yaml
> Chore: Update GitHub setup-python action from v4 -> v5

- .github/workflows/composed-gradle-nexus-iq.yaml
This workflow runs gradle build and then invokes
Nexus IQ for scanning.
> CI: Add workflow for gradle CLM evaluation

- .github/workflows/composed-gradle-nexus-iq.yaml
- Workflow name update
- CLM call step depends on Gradle build step
- Env var needs to be stored in the right format
> Fix: Update gradle clm workflow with few fixes:

- .github/workflows/composed-gradle-nexus-iq.yaml
Typo, fix "_" to "-" in application ID
> Fix: Nexus application ID should be all dashed

- .github/actions/gradle-build-action/action.yaml
Remove variables from ID.
Add shell: bash in run build command
> Fix: Fix gradle action

- .github/actions/maven-build-action/action.yaml
- .github/workflows/compose-maven-verify.yaml
- .github/workflows/composed-maven-nexus-iq.yaml
Refactor Maven build as a reusable action.
This will allow us to call it easier in other Maven based workflows.
> CI: Refactor Maven build

- .github/workflows/composed-tox-sonar-cloud.yaml
This workflow runs a tox verify and a SonarCloud
code scan.
> CI: Add workflow for tox SonarCloud

- .github/workflows/composed-cmake-sonar-cloud.yaml
> Fix: Run "bash" in cmake Sonar scan script step

- .github/workflows/compose-jjb-verify.yaml
- .github/workflows/gerrit-ci-management-merge.yaml
- .github/workflows/gerrit-ci-management-verify.yaml
- .github/workflows/gerrit-compose-ci-management-verify.yaml
JJB 6.3.0 is released and includes bug fixes and improvements on job views.
Ref:
https://groups.google.com/g/jenkins-job-builder/c/d4PPKsGGab0
> Chore: Update JJB to 6.3.0

- .github/workflows/compose-packer-verify.yaml
Ref:
https://github.com/actions/runner/issues/807#issuecomment-916236648
> Fix: Mask secrets from console env on GHA

- .github/workflows/compose-gradle-publish.yaml
This workflow will run gradle build and publish the artifacts produced in a given location.
> CI: Add workflow for gradle publish artifacts

- .github/workflows/compose-packer-verify.yaml
Ensure a multiline strings are output in the correct format to GITHUB_ENV.
> Fix: Check and handle multiline values

- .github/workflows/call-gerrit-nodejs-sonatype-lifecycle.yaml
- .github/workflows/reuse-sonatype-lifecycle.yaml
Runs Sonatype Lifecycle scans on Node.js projects.
Required for ONAP, e.g. portal-ng-ui repository.
> Feat: Add a new reusable workflow for Sonatype Lifecycle

- .github/dependabot.yml
> CI: Enable dependabot

- .github/actions/openssf-scorecard-summary-action/README.md
- .github/actions/openssf-scorecard-summary-action/action.yaml
Tested: https://github.com/os-climate/osc-github-devops/actions/runs/13222496570
> Feat: Implement OpenSSF summary output as action

- .github/workflows/dependency-review.yml
This pull request is created by [StepSecurity](https://app.stepsecurity.io/securerepo) at the request of @tykeal. Please merge the Pull Request to incorporate the requested changes. Please tag @tykeal on your message if you have any questions related to the PR.
The Dependency Review Workflow enforces dependency reviews on your pull requests. The action scans for vulnerable versions of dependencies introduced by package version changes in pull requests, and warns you about the associated
security vulnerabilities. This gives you better visibility of what's changing in a pull request, and helps prevent vulnerabilities being added to your repository.
- [Github Guide about Dependency Review](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/ …
> CI: Apply security best practices

- .github/actions/standalone-linting-action/README.md
- .github/actions/standalone-linting-action/action.yaml
- .github/actions/standalone-linting-action/pre-commit-config.yaml
- .github/actions/standalone-linting-action/requirements.txt
See workflow code/implementation here:
https://github.com/os-climate/osc-github-devops/blob/main/.github/workflows/reuse-linting.yaml
Running as a workflow:
https://github.com/os-climate/osc-github-devops/actions/runs/13265228924/job/37030887868?pr=585
> Feat: Add standalone linting action

- .github/actions/sonarqube-cloud-scan-action/README.md
- .github/actions/sonarqube-cloud-scan-action/action.yaml
Improves documentation with regard to scan behaviour and key points regarding scan configuration files and options. Fixes spacing of example workflow YAML code.
> Fix: Do not pass scan arguments, instead create configuration file

- .github/workflows/reuse-standalone-linting.yaml
Addresses https://github.com/lfit/releng-reusable-workflows/issues/245
> Chore: bump version of called action for standalone linting reusable wf

- .github/workflows/composed-tox-sonar-cloud.yaml
Uses the latest upstream version of the SonarQube Cloud action.
Addresses a syntax error with the reusable workflow call.
Issue: Fixes #249
> Fix: Update composed-tox-sonar-cloud.yaml

- .github/workflows/reuse-sonarqube-cloud.yaml
New version uses refactored download action
> Fix: Use newer sonarqube action

- .github/workflows/reuse-sonarqube-cloud.yaml
- .github/workflows/reuse-sonatype-lifecycle.yaml
- Updated upstream action references/location
- Standardized input case
- Complete input mapping: all action inputs correctly passed through
- Default values now aligned with upstream actions
> Chore: Update scans (Sonatype/Sonarqube) to use lfreleng-actions
